name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  terraform_plan:
    runs-on: ubuntu-20.04
    name: Terraform Plan
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout tfmake
      uses: actions/checkout@v3
      with:
        repository: tfmake/tfmake
        path: terraform/tfmake

    - name: Install tfmake
      run: |
        sudo cp -r tfmake/usr/* /usr/
        sudo chmod +x /usr/local/bin/tfmake
        rm -rf tfmake

    - name: Get all changed files
      id: changed_files
      uses: tj-actions/changed-files@v35
      with:
        path: terraform
        diff_relative: true
        files: |
          **/*.tf
          **/*.tfvars

    - run: tfmake setup

    - run: tfmake init --plan

    - name: Run tfmake touch
      run: tfmake touch "${FILES}"
      env:
        FILES: ${{ steps.changed_files.outputs.all_changed_files }}

    - run: tfmake makefile --plan

    - run: tfmake plan
      continue-on-error: true

    - run: tfmake mermaid --plan
      env:
        CLASS_DEF_DEFAULT: ${{ vars.CLASS_DEF_DEFAULT }}
        CLASS_DEF_VISITED: ${{ vars.CLASS_DEF_VISITED }}

    - run: tfmake summary --plan
      env:
      SUMMARY_TITLE: Terraform Plan for Basic project

    - run: tfmake gh-step-summary --plan

    - name: Run tfmake gh-pr-comment --plan
      run: tfmake gh-pr-comment --plan ${NUMBER}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUMBER: ${{ github.event.pull_request.number }}
